name: Secrets & Env
on:
  push:
    branches:
    - main

jobs:
  access-secret:
    runs-on: ubuntu-latest
    
    steps:
       - name: Checkout code
         uses: actions/checkout@v2
        
       - name: Use the secret in JavaScript code
         run: |
          echo "${{ secrets.USERNAME }}"
          echo "${{ secrets.PASSWORD }}"
