name: Secrets & Env
on:
  push:
    branches:
    - main

jobs:
  get_Secrets:
    runs-on: ubuntu-latest

    env:
      USERNAME: ${{secrets.USERNAME}}
      PASSWORD: ${{secrets.PASSWORD}}
    
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      
      - name: Build and deploy
        run: |
